# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1

# The assistant project unique identifier
# This default value must be replaced with a unique assistant name within your deployment
assistant_id: 20231212-120438-mechanical-energy

# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: ru

pipeline:
  - name: WhitespaceTokenizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: CountVectorsFeaturizer
  - name: DIETClassifier
    epochs: 50
    num_transformer_layers: 4
    transformer_size: 256
    use_masked_language_model: true
    drop_rate: 0.25
    weight_sparsity: 0.7
    batch_size: [64, 256]
    embedding_dimension: 100
    hidden_layer_sizes:
      text: [512, 128]

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: "RulePolicy"
    core_fallback_threshold: 0.5
    core_fallback_action_name: action_default_fallback
    enable_fallback_prediction: true
    restrict_rules: true
    check_for_contradictions: true
  - name: TEDPolicy
    max_history: 5
    epochs: 100
    constrain_similarities: true
