version: "3"

services:
  minio:
    image: minio/minio:latest
    volumes:
      - minio-data./data
    environment:
      MINIO_ROOT_USER: minioaccesskey
      MINIO_ROOT_PASSWORD: miniosecretkey
    command: server /data
    ports:
      - "9000:9000"